[fix] Conjure ObjectMapper does not follow spec in serialising optional properties
palantir/conjure-java-runtime pull request #1127
Opened 2019-06-11 13:40 UTC by JacekLach

## Before this PR

`OptionalExample.empty()` serializes as `{"value"=null}`
## After this PR
>Keys are obtained from the Conjure object's fields and values using JSON(v). For any (key,value) pair where the value is of optional<?> type, the key must be omitted from the JSON Object if the value is absent.

https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#53-named-types

==COMMIT_MSG==
Conjure ObjectMappers no longer produce null map values when serialising absent properties on conjure objects.
==COMMIT_MSG==

## Possible downsides?
Breaks some tests where people wrote generated maps on disk, I guess.

2019-07-30 16:49 UTC, dansanduleac commented
👍

2019-07-31 10:38 UTC, ferozco requested changes
Thinking about this more, I don't think we should merge this change since it will break users that return responses with null values. This typically happens when endpoints return raw data (rows in a dataset, values in a timeseries, etc) rather than structure conjure responses.

2019-07-31 12:10 UTC, JacekLach commented
Why are people using a conjure mapper to serialise non-conjure responses?

2019-08-15 22:44 UTC, pkoenig10 commented on conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
> +                .setSerializationInclusion(JsonInclude.Include.NON_NULL)
Instead we should probably use `NON_ABSENT` and remove the `configureAbsentsAsNulls` config below. This is what the docs recommend:
https://github.com/FasterXML/jackson-modules-java8/blob/jackson-modules-java8-2.9.9/datatypes/src/main/java/com/fasterxml/jackson/datatype/jdk8/Jdk8Module.java#L21-L23

2019-08-15 22:48 UTC, pkoenig10 commented on conjure-java-jackson-serialization/src/main/java/com/palantir/conjure/java/serialization/ObjectMappers.java
> +                .setSerializationInclusion(JsonInclude.Include.NON_NULL)
We should also probably just use `setDefaultPropertyInclusion(...)` instead. `setSerializationInclusion` is a just convenience method that calls `setPropertyInclusion` which is deprecated in favor of `setDefaultPropertyInclusion`.

2019-09-30 16:47 UTC, closed without merging