Add ability to create a TrustContext from PEM/DER certs in memory
palantir/conjure-java-runtime pull request #249
Opened 2016-10-11 22:05 UTC by jared2501

2016-10-11 22:21 UTC, markelliot requested changes
not a huge fan of the code duplication, but probably needs a slightly bigger refactor to eliminate it, and probably isn't worth the refactor. (ie could have a `CertificateCreationStrategy<T>` and then create fixed instances of it to pass to the other methods, meh)

2016-10-11 22:21 UTC, markelliot commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +                        entry.getKey(), readX509Certificate(new ByteArrayInputStream(entry.getValue())));
you don't close the BAIS

2016-10-11 22:21 UTC, markelliot commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
>              keyStore.load(null, null);
these two lines should mirror the function above, which catch the exception near here and provide more granular per-certificate exception handling below

2016-10-11 22:21 UTC, markelliot commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +    static KeyStore createTrustStoreFromCertificates(Map<String, byte[]> certificatesByAlias) {
I think `byte[]` is probably a weird way to carry the certificate bytes, maybe we should make an alias object so it's obvious what it is?

2016-10-11 22:24 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +    static KeyStore createTrustStoreFromCertificates(Map<String, byte[]> certificatesByAlias) {
Sweet - how does `PemX509Certificate` sound as alias?

2016-10-11 22:24 UTC, markelliot commented
Works for me.

2016-10-11 22:45 UTC, uschi2000 commented
wow, this github diff is quite terrible :(

2016-10-11 22:49 UTC, uschi2000 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslSocketFactories.java
> +    public static SSLSocketFactory createSslSocketFactory(Map<String, byte[]> trustCertificatesByAlias) {
needs docs

2016-10-11 22:49 UTC, uschi2000 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslSocketFactories.java
> +    public static SSLSocketFactory createSslSocketFactory(Map<String, byte[]> trustCertificatesByAlias) {
you'll have to explain somewhere what exactly you mean by "trustCertificatesByAlias"

2016-10-12 01:26 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +                        entry.getKey(), readX509Certificate(new ByteArrayInputStream(entry.getValue())));
technically, the close method on the BAIS does nothing:

```
public void close() throws IOException {
    }
```

2016-10-12 01:30 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +    static KeyStore createTrustStoreFromCertificates(Map<String, byte[]> certificatesByAlias) {
done

2016-10-12 02:34 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
>              keyStore.load(null, null);
done

2016-10-12 02:34 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +    static KeyStore createTrustStoreFromCertificates(Map<String, byte[]> certificatesByAlias) {
done

2016-10-12 02:34 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +                        entry.getKey(), readX509Certificate(new ByteArrayInputStream(entry.getValue())));
done

2016-10-12 02:34 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslSocketFactories.java
> +    public static SSLSocketFactory createSslSocketFactory(Map<String, byte[]> trustCertificatesByAlias) {
done

2016-10-12 03:05 UTC, jared2501 commented
addressed comments

2016-10-12 03:10 UTC, markelliot requested changes

2016-10-12 03:10 UTC, markelliot commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +        }
pull out this block of code into `private static KeyStore createKeyStore()`

2016-10-12 03:10 UTC, markelliot commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslSocketFactories.java
> +        }
guessing this block of code also repeated: `private static SSLContext createSslContextFromTrustManagers(TrustManager[] trustManagers)`?

2016-10-12 03:17 UTC, jared2501 reviewed
done review

2016-10-12 03:17 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/KeyStores.java
> +        }
done

2016-10-12 03:17 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslSocketFactories.java
> +        }
done

2016-10-12 03:19 UTC, markelliot reviewed
lgtm, Rob?

2016-10-12 16:01 UTC, uschi2000 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> +    public abstract String pemCertificate();
what's the deal here with those PEM headers, something like `---PUBLIC KEY---`?

2016-10-12 16:02 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> +    public abstract String pemCertificate();
they can be anything - `PUBLIC KEY`, `CERTIFICATE`, etc.. I don't think it actually matters. Can write test if you wish?

2016-10-12 16:04 UTC, uschi2000 commented
just add a comment, maybe?

On Wed, Oct 12, 2016 at 9:02 AM jared2501 <notifications@github.com> wrote:

> *@jared2501* commented on this pull request.
> ------------------------------
>
> In
> ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> <https://github.com/palantir/http-remoting/pull/249>:
>
> > + */
> +
> +package com.palantir.remoting1.config.ssl;
> +
> +import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
> +import com.fasterxml.jackson.databind.annotation.JsonSerialize;
> +import org.immutables.value.Value;
> +
> +@Value.Immutable
> +@Value.Style(visibility = Value.Style.ImplementationVisibility.PACKAGE, jdkOnly = true)
> +@JsonSerialize(as = ImmutablePemX509Certificate.class)
> +@JsonDeserialize(as = ImmutablePemX509Certificate.class)
> +public abstract class PemX509Certificate {
> +
> +    /** A X509.1 certificate in PEM format encoded in UTF-8. */
> +    public abstract String pemCertificate();
>
> they can be anything - PUBLIC KEY, CERTIFICATE, etc.. I don't think it
> actually matters. Can write test if you wish?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/249>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwXdZJZ2Qrothl0xkaxoN_xmIToPRks5qzQSXgaJpZM4KUJ_4>
> .
>

2016-10-12 16:04 UTC, uschi2000 commented
or a test too if it's simple enough.

On Wed, Oct 12, 2016 at 9:04 AM Robert Fink <rf@robertfink.de> wrote:

> just add a comment, maybe?
>
> On Wed, Oct 12, 2016 at 9:02 AM jared2501 <notifications@github.com>
> wrote:
>
> *@jared2501* commented on this pull request.
> ------------------------------
>
> In
> ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> <https://github.com/palantir/http-remoting/pull/249>:
>
> > + */
> +
> +package com.palantir.remoting1.config.ssl;
> +
> +import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
> +import com.fasterxml.jackson.databind.annotation.JsonSerialize;
> +import org.immutables.value.Value;
> +
> +@Value.Immutable
> +@Value.Style(visibility = Value.Style.ImplementationVisibility.PACKAGE, jdkOnly = true)
> +@JsonSerialize(as = ImmutablePemX509Certificate.class)
> +@JsonDeserialize(as = ImmutablePemX509Certificate.class)
> +public abstract class PemX509Certificate {
> +
> +    /** A X509.1 certificate in PEM format encoded in UTF-8. */
> +    public abstract String pemCertificate();
>
> they can be anything - PUBLIC KEY, CERTIFICATE, etc.. I don't think it
> actually matters. Can write test if you wish?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/249>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwXdZJZ2Qrothl0xkaxoN_xmIToPRks5qzQSXgaJpZM4KUJ_4>
> .
>
>

2016-10-12 16:13 UTC, nmiyake commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> +    public abstract String pemCertificate();
Haven't verified behavior myself, but sounds like content after `BEGIN` and `END` may matter -- see https://tools.ietf.org/html/rfc7468#page-11 and http://stackoverflow.com/a/5356351. May be worth verifying/investigating.

2016-10-12 16:14 UTC, jared2501 commented on ssl-config/src/main/java/com/palantir/remoting1/config/ssl/PemX509Certificate.java
> +    public abstract String pemCertificate();
done - added this comment:

```
    /**
     * A X509.1 certificate or certificate chain in PEM format encoded in UTF-8.
     * <p>
     * The certificates must be delimited by the the begin and end {@code CERTIFICATE} markers.
     */

```

2016-10-12 16:46 UTC, uschi2000 approved these changes

2016-10-12 16:46 UTC, uschi2000 commented
@markelliot I think you'll have to "approve" explicitly

2016-10-12 16:47 UTC, markelliot approved these changes

2016-10-12 16:55 UTC, merged