Add tracing aware executor utils
palantir/conjure-java-runtime pull request #258
Opened 2016-10-13 03:04 UTC by markelliot

2016-10-13 03:04 UTC, markelliot commented
@uschi2000

2016-10-13 03:11 UTC, markelliot commented
some atlasdb prior art from its original code base:
https://github.com/palantir/atlasdb/blob/develop/commons-executors/src/main/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocal.java
https://github.com/palantir/atlasdb/blob/develop/commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
(these would be the more generic approach)

2016-10-13 16:40 UTC, uschi2000 requested changes

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareRunnable.java
> +public final class TracingAwareRunnable implements Runnable {
can this be package-private?

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/Traces.java
> +        STATE.get().remove();
this just removes one TraceState, right? don't you need to remove all of them?

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +public final class TracingAwareCallable<V> implements Callable<V> {
can be package-private?

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +        this.state = Traces.getCopyOfState();
I think it'll be more clear if you inject the `state`

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareExecutorService.java
> +        return delegate.invokeAll(Collections2.transform(tasks, new TracedCallableConverter<T>()));
use static instance of converter

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareExecutorService.java
> +        return delegate.invokeAll(Collections2.transform(tasks, new TracedCallableConverter<T>()));
oh, actually that may not work that nicely due to generics?

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareExecutorService.java
> +        return delegate.invokeAll(Collections2.transform(tasks, new TracedCallableConverter<T>()));
this code path is going to be quite hot, so maybe it's worthing avoiding the object creation

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +        this.state = Traces.getCopyOfState();
alternatively, leave a class-level comment: 
```A {@link Callable} that uses the thread-local tracing state at the time of it's construction during its {@link #call execution}. The {@link TracingAwareCallable} constructor is called by a tracing-aware executor service on the same thread on which a user creates a Callable; the {@link call} function is executed on an arbitrary (likely different) thread with different tracing state. In order to execute the task with the original (and intuitively expected) tracing state, we remember the original state and set it for the duration of the {@link #call execution}.
```

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareRunnable.java
> +public final class TracingAwareRunnable implements Runnable {
add a `See {@link TracingAwareCallable}` comment

2016-10-13 16:40 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/Traces.java
> +        STATE.get().remove();
we should some tests for this ...

2016-10-13 23:36 UTC, markelliot commented
do you want to take this over?

2016-10-13 23:37 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +public final class TracingAwareCallable<V> implements Callable<V> {
Probably want to provide a way to wrap a `Callable<V>` generally, fine with that being a utility class that hides this implementation. Maybe the utility class should nest these implementations as private static classes?

2016-10-13 23:38 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +        this.state = Traces.getCopyOfState();
utility class mentioned in previous comment would make it more apparent how to do the wrapping and more obvious that the state is being injected. The main thing is that a caller that needs to wrap their `Callable<V>` submission should be able to do so without having to know about how to grab present state.

2016-10-13 23:38 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareCallable.java
> +        this.state = Traces.getCopyOfState();
Speaking of which, I suspect we probably want to do something in the ExecutorService implementations that checks if the callable being passed is already an implementation of this, so we can avoid the duplicate work.

2016-10-13 23:39 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/TracingAwareExecutorService.java
> +        return delegate.invokeAll(Collections2.transform(tasks, new TracedCallableConverter<T>()));
unfortunately the `<T>` makes this very hard. `invokeAll` likely isn't a hot code path, though, the `Callable<T>`s are likely the bulk of the work.

2016-10-17 16:48 UTC, markelliot commented
obe

2016-10-17 16:48 UTC, closed without merging