Added cookie management in retrofit client
palantir/conjure-java-runtime pull request #263
Opened 2016-10-14 00:24 UTC by mdambros

Added cookie manager, using configs to set which cookies to accept based on:

- originating host, providing a list of allowed ones
- cookie name, providing a list of regex for the allowed names

2016-10-14 00:24 UTC, palantirtech commented
Thanks for your interest in [palantir/http-remoting](https://github.com/palantir/http-remoting), @mdambros! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2016-10-14 00:32 UTC, mdambros commented
@pnepywoda could you have a look at this? Only a starting point for PDS-46177, but interested to see if this is going in the right direction.

Thanks!

2016-10-16 12:04 UTC, mdambros commented
@uschi2000 could you have a look at this PR? The goal is to make http-remoting based services work behind a proxy which requires cookies (as for example a particular configuration of blue coat proxy: https://forums.bluecoat.com/forum/security-policy-enforcement-center/proxysg/30375-bcsi-cookie-on-reverse-proxy)

2016-10-17 14:38 UTC, uschi2000 commented
Looking

2016-10-17 14:46 UTC, uschi2000 requested changes

2016-10-17 14:46 UTC, uschi2000 commented on jaxrs-clients/build.gradle
> +    compile "com.squareup.okhttp3:okhttp-urlconnection:3.0.0-RC1"
Is this versions independently from okhttp3?

2016-10-17 14:46 UTC, uschi2000 commented on jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/FeignJaxRsClientBuilder.java
> +import okhttp3.internal.JavaNetCookieJar;
Is there no public OK http API for cookies?

2016-10-17 14:46 UTC, uschi2000 commented on jaxrs-clients/src/main/java/com/palantir/remoting1/jaxrs/FeignJaxRsClientBuilder.java
> +                    for (String nameRegex : config.allowedCookieNameRegex().get()) {
Need to precompile these regular expressions into patterns

2016-10-17 14:46 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/Retrofit2ClientBuilder.java
> +        CookieHandler.setDefault(cm);
This is a little scary. What does it do and why do we need to set static state?

2016-10-17 14:46 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting1/retrofit2/Retrofit2ClientBuilder.java
> +        CookieManager cm = new CookieManager(null, new CookiePolicy(){
Factor out duplicate code

2016-10-17 14:46 UTC, uschi2000 commented on service-config/src/main/java/com/palantir/remoting1/config/service/ServiceConfiguration.java
> +    public abstract Optional<List<String>> allowedCookieNameRegex();
Would prefer allowedCookieNames

2016-10-17 14:47 UTC, uschi2000 commented
Also, this needs test coverage.

2017-01-20 14:21 UTC, uschi2000 commented
Closing since there wasn't much movement

2017-01-20 14:21 UTC, closed without merging