Add method for creating an SSLContext that merges both the trust store and custom certificates
palantir/conjure-java-runtime pull request #2677
Opened 2023-08-14 13:25 UTC by Eric-Alvarez

## Before this PR

## After this PR

==COMMIT_MSG==
==COMMIT_MSG==

## Possible downsides?

2023-08-14 13:30 UTC, Eric-Alvarez commented on keystores/src/main/java/com/palantir/conjure/java/config/ssl/SslSocketFactories.java
> +    public static SSLSocketFactory createSslSocketFactory(
I noticed most of these methods aren't explicitly tested, do I need to add tests for my additions?

2023-08-14 13:31 UTC, Eric-Alvarez commented on keystores/src/main/java/com/palantir/conjure/java/config/ssl/SslSocketFactories.java
> +    private static KeyStore getCombinedTrustStoreAndDefaultCas(Path trustStorePath, StoreType trustStoreType) {
This would be convenient if we made it public, this PR would not be necessary if this method was available.

2023-08-14 17:00 UTC, pkoenig10 requested changes, later dismissed
I would prefer not to add these methods.

The use case seems very niche and they introduce a fairly large footgun. I don't want to implicitly endorse adding custom certificates to truststore. Doing so makes it very hard to reason about the security of our services because can no longer be sure that the truststore being used by the application matches what is rendered by our production infrastructure.

For your use case, I'd recommend just writing this yourself.

2023-08-14 18:39 UTC, Eric-Alvarez commented
@pkoenig10 I'm happy to not add the top level methods, but exposing the ability to load a keystore from a truststore with default ca certs is innocuous and very useful for handling these edge cases.

2023-08-14 18:57 UTC, Eric-Alvarez commented
@pkoenig10 Could you take a look at the update? Making this method accessible will eliminate the need to copy paste a lot of code for loading truststores and default ca certs (although the latter can be handled with adding the jvm_certs into the trust store). I'd rather not copy paste the method for loading truststores as it will become out of date and might fail in the future.

2023-08-14 18:57 UTC, Eric-Alvarez commented on keystores/src/main/java/com/palantir/conjure/java/config/ssl/KeyStores.java
> +    public static KeyStore getCombinedTrustStoreAndDefaultCas(Path trustStorePath, StoreType trustStoreType) {
Unsure if it would be preferred to put this in a different class rather than making this public.

2023-08-14 21:00 UTC, pkoenig10 commented
I'd like to better understand why we think this behavior should be provided by this library. This library is intended to be a utility to create Conjure clients, not a general keystore library.

APIs live forever and can be (ab)used in unexpected ways, so I generally hold a pretty high bar when adding new APIs. I'm not convinced that this behavior crosses that threshold. This behavior is fairly niche and I don't think it's unreasonable to require consumers who want this behavior to implement it themselves.

Addressing some specific comments:

> Making this method accessible will eliminate the need to copy paste a lot of code for loading truststores and default ca certs

What is the problem with duplicating this code? Duplicating code is preferable to providing a possibly dangerous API that can be misused.

> I'd rather not copy paste the method for loading truststores as it will become out of date and might fail in the future.

Can you explain what you mean by "out of date"? What specific failure modes are you concerned about?

2023-08-15 18:02 UTC, Eric-Alvarez commented
Security vulnerabilities, performance improvements, and adding/removing keystore types are all areas that could be a concern with duplicating the code. 
It seems this library _is_ a generic trust store/key store library for the most part. There's no mention of conjure outside of package names in the whole thing. And the return types are generic java types rather than anything specific to conjure clients.

We have a standard truststore format, it would be nice if we were able to load it without copy pasting code from another repo that could break or become insecure. Loading a truststore or keystore seems like a pretty normal use-case that could be re-used in many places. Taking a hard line that we're not allowed to iterate on or use any keystore utilities and everything needs to be copy pasted seems like an objectively worse state of the world.
I'm not sure I see the risk of abuse with simply providing a convenience method to return a loaded keystore, as you mentioned I am completely able to do this already, just in a worse way that could add bugs or be insecure.

2025-06-27 11:47 UTC, closed without merging