AsyncSlf4jSpanObserverTest logs Zipkin-compatible spans
palantir/conjure-java-runtime pull request #278
Opened 2016-10-21 21:11 UTC by uschi2000

2016-10-21 21:27 UTC, markelliot requested changes

2016-10-21 21:27 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> +        static long nanoToMilli(long nano) {
This converts to microseconds, right?

2016-10-21 22:54 UTC, markelliot commented on tracing/src/main/java/com/palantir/remoting1/tracing/OpenSpan.java
> +    public abstract long getStartTimeMicroSeconds();
probably worth modifying Span to match

2016-10-21 23:11 UTC, markelliot approved these changes

2016-10-21 23:24 UTC, schlosna commented on tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
>              return (long) Math.ceil(nano / (double) 1000);
Why are we doing double math here? This should be:

`return Math.max(1L, nano / 1000L);`

2016-10-21 23:24 UTC, schlosna commented on tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> +            return (long) Math.ceil(nano / (double) 1000);
Why are we doing double math here? This should be:

`return Math.max(1L, nano / 1000L);`

2016-10-21 23:24 UTC, schlosna commented on tracing/src/main/java/com/palantir/remoting1/tracing/Tracers.java
> +        return Strings.padStart(Long.toHexString(number), 16, '0');
Curious why we're padding

2016-10-21 23:24 UTC, schlosna commented on tracing/src/test/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserverTest.java
> +        assertThat(AsyncSlf4jSpanObserver.ZipkinCompatibleSerializableSpan.nanoToMicro(0)).isEqualTo(0);
Per https://github.com/openzipkin/zipkin-api/blob/master/zipkin-api.yaml#L281 I think you have to round up to 1 microsecond

See also https://github.com/openzipkin/zipkin/issues/1174

2016-10-21 23:38 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/Tracers.java
> +        return Strings.padStart(Long.toHexString(number), 16, '0');
that's what zipkin does

2016-10-21 23:39 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> +            return (long) Math.ceil(nano / (double) 1000);
assume i should round up instead of truncate?

2016-10-21 23:39 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> +            return (long) Math.ceil(nano / (double) 1000);
will add the max

2016-10-21 23:50 UTC, uschi2000 commented on tracing/src/main/java/com/palantir/remoting1/tracing/OpenSpan.java
> +    public abstract long getStartTimeMicroSeconds();
done

2016-10-22 00:07 UTC, merged

2016-10-25 18:12 UTC, uschi2000 commented
done

On Fri, Oct 21, 2016 at 3:54 PM Mark Elliot <notifications@github.com>
wrote:

> *@markelliot* commented on this pull request.
> ------------------------------
>
> In tracing/src/main/java/com/palantir/remoting1/tracing/OpenSpan.java
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5332363>
> :
>
> >       * <p>
>       * Users of this class should not set this value manually in the builder, it is configured
>       * automatically when using the {@link #builder()} static.
>       */
> -    public abstract long getStartTimeMs();
> +    public abstract long getStartTimeMicroSeconds();
>
> probably worth modifying Span to match
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5332363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwR3AnKE59YTczf765uh5D2VkzL_iks5q2UKpgaJpZM4Kdl7W>
> .
>

2016-10-25 18:18 UTC, uschi2000 commented
correct.

On Fri, Oct 21, 2016 at 2:27 PM Mark Elliot <notifications@github.com>
wrote:

> *@markelliot* requested changes on this pull request.
> ------------------------------
>
> In
> tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>
> :
>
> > +        abstract Optional<String> getParentId();
> +        abstract long getTimestamp();
> +        abstract long getDuration();
> +
> +        static ZipkinCompatibleSerializableSpan fromSpan(Span span) {
> +            return ImmutableZipkinCompatibleSerializableSpan.builder()
> +                    .traceId(span.getTraceId())
> +                    .id(span.getSpanId())
> +                    .name(span.getOperation())
> +                    .parentId(span.getParentSpanId())
> +                    .timestamp(span.getStartTimeMs())
> +                    .duration(nanoToMilli(span.getDurationNs()))  // Zipkin-durations are micro-seconds, rounded up
> +                    .build();
> +        }
> +
> +        static long nanoToMilli(long nano) {
>
> This converts to microseconds, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwVN1BytjshgZxMRMA4VmUWuVZHhFks5q2S4ugaJpZM4Kdl7W>
> .
>

2016-10-25 18:19 UTC, uschi2000 commented
Pushed.

On Fri, Oct 21, 2016 at 3:23 PM Robert Fink <rf@robertfink.de> wrote:

> And yet, it seems that we're making milli seconds in places. will have to
> convert more. Do not merge.
>
> On Fri, Oct 21, 2016 at 3:22 PM Robert Fink <rf@robertfink.de> wrote:
>
> (And double-checked that zipkin wants micro, not milli)
>
> On Fri, Oct 21, 2016 at 3:22 PM Robert Fink <rf@robertfink.de> wrote:
>
> correct.
>
> On Fri, Oct 21, 2016 at 2:27 PM Mark Elliot <notifications@github.com>
> wrote:
>
> *@markelliot* requested changes on this pull request.
> ------------------------------
>
> In
> tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>
> :
>
> > +        abstract Optional<String> getParentId();
> +        abstract long getTimestamp();
> +        abstract long getDuration();
> +
> +        static ZipkinCompatibleSerializableSpan fromSpan(Span span) {
> +            return ImmutableZipkinCompatibleSerializableSpan.builder()
> +                    .traceId(span.getTraceId())
> +                    .id(span.getSpanId())
> +                    .name(span.getOperation())
> +                    .parentId(span.getParentSpanId())
> +                    .timestamp(span.getStartTimeMs())
> +                    .duration(nanoToMilli(span.getDurationNs()))  // Zipkin-durations are micro-seconds, rounded up
> +                    .build();
> +        }
> +
> +        static long nanoToMilli(long nano) {
>
> This converts to microseconds, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwVN1BytjshgZxMRMA4VmUWuVZHhFks5q2S4ugaJpZM4Kdl7W>
> .
>
>

2016-10-25 18:29 UTC, uschi2000 commented
And yet, it seems that we're making milli seconds in places. will have to
convert more. Do not merge.

On Fri, Oct 21, 2016 at 3:22 PM Robert Fink <rf@robertfink.de> wrote:

> (And double-checked that zipkin wants micro, not milli)
>
> On Fri, Oct 21, 2016 at 3:22 PM Robert Fink <rf@robertfink.de> wrote:
>
> correct.
>
> On Fri, Oct 21, 2016 at 2:27 PM Mark Elliot <notifications@github.com>
> wrote:
>
> *@markelliot* requested changes on this pull request.
> ------------------------------
>
> In
> tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>
> :
>
> > +        abstract Optional<String> getParentId();
> +        abstract long getTimestamp();
> +        abstract long getDuration();
> +
> +        static ZipkinCompatibleSerializableSpan fromSpan(Span span) {
> +            return ImmutableZipkinCompatibleSerializableSpan.builder()
> +                    .traceId(span.getTraceId())
> +                    .id(span.getSpanId())
> +                    .name(span.getOperation())
> +                    .parentId(span.getParentSpanId())
> +                    .timestamp(span.getStartTimeMs())
> +                    .duration(nanoToMilli(span.getDurationNs()))  // Zipkin-durations are micro-seconds, rounded up
> +                    .build();
> +        }
> +
> +        static long nanoToMilli(long nano) {
>
> This converts to microseconds, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwVN1BytjshgZxMRMA4VmUWuVZHhFks5q2S4ugaJpZM4Kdl7W>
> .
>
>

2016-10-25 18:54 UTC, uschi2000 commented
(And double-checked that zipkin wants micro, not milli)

On Fri, Oct 21, 2016 at 3:22 PM Robert Fink <rf@robertfink.de> wrote:

> correct.
>
> On Fri, Oct 21, 2016 at 2:27 PM Mark Elliot <notifications@github.com>
> wrote:
>
> *@markelliot* requested changes on this pull request.
> ------------------------------
>
> In
> tracing/src/main/java/com/palantir/remoting1/tracing/AsyncSlf4jSpanObserver.java
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>
> :
>
> > +        abstract Optional<String> getParentId();
> +        abstract long getTimestamp();
> +        abstract long getDuration();
> +
> +        static ZipkinCompatibleSerializableSpan fromSpan(Span span) {
> +            return ImmutableZipkinCompatibleSerializableSpan.builder()
> +                    .traceId(span.getTraceId())
> +                    .id(span.getSpanId())
> +                    .name(span.getOperation())
> +                    .parentId(span.getParentSpanId())
> +                    .timestamp(span.getStartTimeMs())
> +                    .duration(nanoToMilli(span.getDurationNs()))  // Zipkin-durations are micro-seconds, rounded up
> +                    .build();
> +        }
> +
> +        static long nanoToMilli(long nano) {
>
> This converts to microseconds, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/278#pullrequestreview-5322415>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwVN1BytjshgZxMRMA4VmUWuVZHhFks5q2S4ugaJpZM4Kdl7W>
> .
>
>