Make JsonExceptionMapper public
palantir/conjure-java-runtime pull request #286
Opened 2016-10-31 15:39 UTC by JiahuiJiang

So that users can extend JsonExceptionMapper with other exception types

2016-10-31 16:06 UTC, markelliot commented
What are some examples of exceptions that are not being mapped that need to be?

2016-10-31 16:07 UTC, uschi2000 requested changes
i'm fine with this, modulo the private MAPPER

2016-10-31 16:07 UTC, uschi2000 commented on jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java
> +    private static final Logger log = LoggerFactory.getLogger(JsonExceptionMapper.class);
not sure why the order changed here, but i guess that doesn't matter?

2016-10-31 16:07 UTC, uschi2000 commented on jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java
> +    protected static final ObjectMapper MAPPER = getObjectMapper();
if we expose this class outside the library, then the exception mapper must be made private. 
also, consider using `ObjectMappers.guavaJdk7().enable(SerializationFeature.INDENT_OUTPUT) in this class and in RemoteExceptionMapper.

2016-10-31 16:16 UTC, schlosna commented on jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java
> +    protected static final ObjectMapper MAPPER = getObjectMapper();
We need a better way to share/inject a global ObjectMapper because right now they're buried in the JAX-RS & Retrofit2 client modules, and we are not consistent with how they are created and what modules are registered, see #284

2016-10-31 19:18 UTC, jiahuijiang commented on jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java
> +    private static final Logger log = LoggerFactory.getLogger(JsonExceptionMapper.class);
Sorted the protected field before the private field. Will change it back when changing the visibility to minimize the diff

2016-10-31 19:22 UTC, JiahuiJiang commented
we are using `JsonParseExceptionMapper` and `JsonMappingExceptionMapper`

2016-11-01 01:45 UTC, uschi2000 commented
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 41 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVQOFi_WMvDOLpv2neV-r1-41:-KVSY9m3wUqwFBLGIv4l:buomj5e) ([raw file](https://github.com/palantir/http-remoting/blob/f480463bc2cb187badbb4b2bf6ee9ddaa8efa5f3/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L41)):*
<details><summary><i>Previously, schlosna (David Schlosnagle) wrote…</i></summary>
> We need a better way to share/inject a global ObjectMapper because right now they're buried in the JAX-RS & Retrofit2 client modules, and we are not consistent with how they are created and what modules are registered, see #284 
</details>
Do you have ideas for how to best do that, David?

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 90 at r3](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVSYKwTw60JpVt-j77F:-KVSYKwTw60JpVt-j77G:b-iltr3j) ([raw file](https://github.com/palantir/http-remoting/blob/66534aaeb73707747da9b013d5007f01476afad6/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L90)):*
> ```Java
>     protected abstract StatusType getStatus(T exception);
> 
>     protected static ObjectMapper getObjectMapper() {
> ```

this is not OK; sub-classes must not have access to the object mapper. probably safest to remove this method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286)*
<!-- Sent from Reviewable.io -->

2016-11-01 14:36 UTC, JiahuiJiang commented
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 90 at r3](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVSYKwTw60JpVt-j77F:-KVVJOUb5BTOGSXipAXy:bvghfh4) ([raw file](https://github.com/palantir/http-remoting/blob/66534aaeb73707747da9b013d5007f01476afad6/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L90)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary>
> this is not OK; sub-classes must not have access to the object mapper. probably safest to remove this method.
</details>
`RemoteExceptionMapper` is using this object mapper to serialize the exception

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286)*
<!-- Sent from Reviewable.io -->

2016-11-01 14:51 UTC, schlosna commented
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 41 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVQOFi_WMvDOLpv2neV-r1-41:-KVVLJROP83BBumtJ-7j:bavevu1) ([raw file](https://github.com/palantir/http-remoting/blob/f480463bc2cb187badbb4b2bf6ee9ddaa8efa5f3/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L41)):*
<details><summary><i>Previously, uschi2000 (Robert Fink) wrote…</i></summary>
> Do you have ideas for how to best do that, David?
</details>
We could have a shared module between the clients & servers modules that provides access to a single shared ObjectMapper. I probably lean more toward the camp where if an application absolutely needs to override the single shared ObjectMapper we allow them to (e.g. to workaround possible Jackson bug or security issue), with the caveat that they're breaking glass and voiding their warranty, and potentially breaking JSON interoperability. This is another reason while something like Protobuf or other IDL is preferable, but that's a discussion for another day.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286)*
<!-- Sent from Reviewable.io -->

2016-11-01 20:42 UTC, JiahuiJiang commented
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 90 at r3](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVSYKwTw60JpVt-j77F:-KVWc8e7kcgTeXBQUgPr:bn6nft) ([raw file](https://github.com/palantir/http-remoting/blob/66534aaeb73707747da9b013d5007f01476afad6/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L90)):*
<details><summary><i>Previously, JiahuiJiang wrote…</i></summary>
> `RemoteExceptionMapper` is using this object mapper to serialize the exception
</details>
Created a separate private object mapper in `RemoteExceptionMapper `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286)*
<!-- Sent from Reviewable.io -->

2016-11-02 01:41 UTC, uschi2000 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286#-:-KVXgVnrztEuL9bVflyt:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-11-09 15:58 UTC, JiahuiJiang commented
@uschi2000 are we okay with merging this?
This is one unresolved discussion https://reviewable.io/reviews/palantir/http-remoting/286#-KVQOFi_WMvDOLpv2neV-r1-41 which is out of the scope of this PR

2016-11-09 17:06 UTC, uschi2000 commented
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java, line 41 at r1](https://reviewable.io:443/reviews/palantir/http-remoting/286#-KVQOFi_WMvDOLpv2neV-r1-41:-KW92Uvx00uutiaibfHa:byzfwm4) ([raw file](https://github.com/palantir/http-remoting/blob/f480463bc2cb187badbb4b2bf6ee9ddaa8efa5f3/jersey-servers/src/main/java/com/palantir/remoting1/servers/jersey/JsonExceptionMapper.java#L41)):*
<details><summary><i>Previously, schlosna (David Schlosnagle) wrote…</i></summary>
> We could have a shared module between the clients & servers modules that provides access to a single shared ObjectMapper. I probably lean more toward the camp where if an application absolutely needs to override the single shared ObjectMapper we allow them to (e.g. to workaround possible Jackson bug or security issue), with the caveat that they're breaking glass and voiding their warranty, and potentially breaking JSON interoperability. This is another reason while something like Protobuf or other IDL is preferable, but that's a discussion for another day.
</details>
ok, will leave that for a future PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/http-remoting/286)*
<!-- Sent from Reviewable.io -->

2016-11-09 17:06 UTC, uschi2000 commented
yep, can you rebase please?

2016-11-17 23:40 UTC, uschi2000 commented
ping

2016-11-22 03:55 UTC, nathklei commented
Chiming in here - I had this exact problem today to map http://www.dropwizard.io/1.0.4/dropwizard-jersey/apidocs/io/dropwizard/jersey/validation/JerseyViolationException.html (which DW throws if any bean validation triggers).

This one is a bit annoying because you need to unwrap the constraint violations via getConstraintViolations to get a reasonable user facing error.  I'm not sure of a perfect solution here - maybe a protected method getMessageFromException(T exception), defaulting to T.getMessage().

Alternatively I can just create my own ExceptionMapper that serializes the JSON myself.

2016-11-22 03:59 UTC, markelliot commented
The simplest things for this:

(1)     Write your own exception mapper, but then rethrow (this will hit the JsonExceptionMapper)

(2)     Add a specific handler for JerseyViolationException to http-remoting

2016-11-22 04:09 UTC, nathklei commented
Ah, I didn't realize you could chain exception mappers like that. I'll give the first option a shot tomorrow.

2017-01-20 14:20 UTC, uschi2000 commented
Closing for now since there wasn't much movement.

2017-01-20 14:20 UTC, closed without merging

2017-04-24 21:23 UTC, nathklei commented
For completeness here's what I ended up with - it'd be nice if this (or something similar) were added to remoting, but it is a bit coupled to Dropwizard.

I couldn't get mapper chaining to work - e.g. throwing from one mapper being caught by another.

```java

@Provider
public class SerializedJerseyViolationExceptionMapper implements ExceptionMapper<JerseyViolationException> {

    private static final ObjectMapper OBJECT_MAPPER = ObjectMappers
            .newClientObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT);
    private static final Logger logger = LoggerFactory.getLogger(SerializedJerseyViolationExceptionMapper.class);

    @Override
    public Response toResponse(JerseyViolationException exception) {
        final Set<ConstraintViolation<?>> violations = exception.getConstraintViolations();
        logger.error("Error handling request because of constraint violations: {}",
                violations);
        final Invocable invocable = exception.getInvocable();
        final String errorMessage = exception.getConstraintViolations()
                .stream()
                .map(violation -> ConstraintMessage.getMessage(violation, invocable))
                .collect(Collectors.joining(", "));
        final int status = ConstraintMessage.determineStatus(violations, invocable);
        ResponseBuilder builder = Response.status(status);
        SerializableError error = SerializableError.of(errorMessage, exception.getClass().getName());
        try {
            builder.type(MediaType.APPLICATION_JSON);
            String json = OBJECT_MAPPER.writeValueAsString(error);
            builder.entity(json);
        } catch (JsonProcessingException e) {
            logger.warn("Unable to translate exception to json for request", e);
            // simply write out the exception message
            builder = Response.status(status);
            builder.type(MediaType.TEXT_PLAIN);
            builder.entity(error.getMessage());
        }
        return builder.build();
    }

}
```