Retrofit can return CompletableFutures
palantir/conjure-java-runtime pull request #436
Opened 2017-05-24 19:38 UTC by j-baker

Remote calls are currently indistinguishable from local calls, which
makes them hard to use.

Additionally, Retrofit currently sucks to use; the Call api is hard
to use and throws IOExceptions.

This lets it return CompletableFutures, which is better than Feign
and

All of the AsyncCallTracker crap is just there to maintain backcompat;
the current method used to throw a RemoteException is wholly
incompatible with anything async.

2017-05-24 19:41 UTC, j-baker commented
@markelliot is this the right way to copy Apache 2 code from other places? I remember you knowing how to do this a while back.

Also, I'm sorry about the glaring hack, but I'm not sure there's any other way to do it :(

2017-05-24 21:13 UTC, uschi2000 requested changes
this doesn't exactly make the retrofit library prettier :(
as an alternative, could we make a static utility that takes a `retrofit2.Call<T>` and turns it into a `CompletableFuture<T>`?

2017-05-24 21:13 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/DefaultAsyncCallTracker.java
> +    public boolean isAsyncRequest(Request request) {
can we guarantee that this gets called exactly once per registerAsyncCall ?

2017-05-24 21:13 UTC, uschi2000 commented on retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/Retrofit2ClientApiTest.java
> +            fail();
use `assertThatThrownBy` (rest of this class uses assertj, i think)

2017-05-24 21:13 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/AsyncCallTracker.java
> +public interface AsyncCallTracker {
minimal docs, explain why we need this.

2017-05-24 21:13 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
> +                        InputStream body = response.errorBody().byteStream();
can byteStream be null?

2017-05-24 21:40 UTC, j-baker commented on retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/Retrofit2ClientApiTest.java
> +            fail();
you can't assert all that much of the cause, sadly

2017-05-24 21:41 UTC, j-baker commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
> +                        InputStream body = response.errorBody().byteStream();
Don't think so!

2017-05-24 21:43 UTC, j-baker commented
Static utility - no, sadly not. The meat of this is in the request adapter, which is essentially something that takes a call and registers a callback; you can't do better because that's the same interface that Call gives you - in fact, this literally wraps Call.

You could wrap it in something like

```
Call<T> call;
CompletableFuture<T> future = new CompletableFuture<>();
try {
    future.complete(call.execute());
} catch (Exception e) {
    future.completeExceptionally(e);
}
```

but this blocks which subverts most of the purpose of doing this.

2017-05-24 21:44 UTC, j-baker commented on retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/Retrofit2ClientApiTest.java
> +            fail();
equals, instance, message. It's ugly, can't think of a better way than this.

2017-05-24 21:45 UTC, j-baker commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/DefaultAsyncCallTracker.java
> +    public boolean isAsyncRequest(Request request) {
Not without keeping some kind of information about the fact we executed it, which leads to issues.

2017-05-24 21:56 UTC, j-baker commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/AsyncSerializableErrorCallAdapterFactory.java
> +                        InputStream body = response.errorBody().byteStream();
(errorBody can be, but only if isSuccessful is true)

2017-05-24 22:02 UTC, uschi2000 commented
for copying code, you can do what the WrappingExecutorService header does, plus add a link:
```
/*
 * Copied from Guava 18.0; original copyright notice below.
 * ... link
 *
 * ... original license ...
 */
```

2017-05-24 22:03 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/DefaultAsyncCallTracker.java
> +    public boolean isAsyncRequest(Request request) {
ok, then i think we should keep these in a cache with timeout.

2017-05-24 22:05 UTC, uschi2000 commented
i'm not super-sold on the idea of hacking the shit out of retrofit, but i appreciate the future/async is interesting to support. thoughts, @markelliot ?

2017-05-24 22:09 UTC, j-baker commented
also - I definitely accept that this doesn't make the retrofit code any better. However, I also think that this entirely transforms the Retrofit interfaces currently writeable;

it turns

```
Call<String> myCall = service.doSomething(args);
try {
    return myCall.execute();
} catch (IOException e) {
    throw new RuntimeException(e);
}
```

into

```
return service.doSomething(args).join();
```

in the most basic case, or in fancier cases, things like

```
return service1.doSomething(args).thenCombine(service2.doSomething(args2), (res1, res2) -> stuff(res1, res2));
```

2017-05-24 22:19 UTC, j-baker commented
for example of a real world usage, on the project I've been working on we frequently have to open many streams of data concurrently, and it's really common for the programmer to either just block on them all, or become aware it'd be silly and add an executor service to run their blocking calls (frequently static because no one likes doing that). It'd be really awesome if instead of blocking opening three streams, blocking getting the lengths of each of them, and then blocking reading a small amount of metadata from them, we could just do most of the lifting with the CompletionStage api.

2017-05-25 17:05 UTC, j-baker commented
@uschi2000 I made it a fair bit less crazy with a touch of mutability. Now it should be basically palatable, no more 'hacking the shit out of retrofit'.

2017-05-25 17:53 UTC, uschi2000 commented on retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/Retrofit2ClientBuilder.java
> +        Dispatcher dispatcher = new Dispatcher();
sorry, let's keep these in a separate PR.

2017-05-25 17:54 UTC, uschi2000 reviewed
one last comment, otherwise i'm fine with this.

2017-05-25 18:00 UTC, markelliot commented
Before we merge this (and pick up support load for it), one question we should poke at is whether there's a better way to support James' remoting needs. In particular, would 'dialogue' would be a better fit here?

2017-05-25 18:02 UTC, uschi2000 commented
It probably would be, but it's not ready.

On Thu, May 25, 2017 at 11:00 AM Mark Elliot <notifications@github.com>
wrote:

> Before we merge this (and pick up support load for it), one question we
> should poke at is whether there's a better way to support James' remoting
> needs. In particular, would 'dialogue' would be a better fit here?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/436#issuecomment-304079190>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwcy-tAdeNxdlQ1EG1J_VDQHElkQpks5r9cHDgaJpZM4NlktB>
> .
>

2017-05-25 18:43 UTC, markelliot commented
Ok, it’s not obvious to me this is the right way to proceed.

Why can we not wrap synchronous calls with CompletableFutures external to the library, or instead provide the library function that appropriately turns a Call<T> into a CompletableFuture<T>?

2017-05-25 18:47 UTC, uschi2000 commented
That was my suggestion above.

On Thu, May 25, 2017 at 11:43 AM Mark Elliot <notifications@github.com>
wrote:

> Ok, it’s not obvious to me this is the right way to proceed.
>
> Why can we not wrap synchronous calls with CompletableFutures external to
> the library, or instead provide the library function that appropriately
> turns a Call<T> into a CompletableFuture<T>?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/palantir/http-remoting/pull/436#issuecomment-304090472>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGOdwet0EDesSxcjFo-82kWiiayTgYMCks5r9cvUgaJpZM4NlktB>
> .
>

2017-05-25 18:52 UTC, markelliot commented
Hm, actually, why are you unable to use https://square.github.io/retrofit/2.x/retrofit/retrofit2/Call.html#enqueue-retrofit2.Callback- ?

2017-05-25 18:52 UTC, j-baker commented
The RemoteException thing breaks Callback.

2017-05-25 18:53 UTC, markelliot commented
I don't understand why, sorry.

2017-05-25 18:54 UTC, j-baker commented
I documented why here: https://github.com/palantir/http-remoting/pull/436/files#diff-e75d19c49d5d16f39054b6a769305f37R22 it's the same reason

2017-05-25 18:58 UTC, uschi2000 commented
Can we re-architect the thing so it throws exceptions in synchronous mode, but plays nicely with the `enqueue()` async mode?

2017-05-25 18:59 UTC, uschi2000 commented
alternatively, stop throwing exceptions if that's how retrofit is meant to be used.

2017-05-25 19:05 UTC, j-baker commented
So in terms of wrapping the synchronous calls external to the library - explicitly I'm trying to achieve more parallelism because there are plenty of places where we do 10 remote calls in a row before being able to consume any data - so if I were to do that I'd have to create my own thread pools and pass them in to each usage site. At the moment, the code I'm looking at has a bunch of static executor services, and I'd rather use the retrofit built in thread pool for this.

I'm hooking this in in the way Retrofit hopes people do this - see https://github.com/square/retrofit/blob/master/retrofit-adapters/java8/src/test/java/retrofit2/adapter/java8/Java8CallAdapterFactoryTest.java - it's the idiomatic way to do it, with a pretty straightforward hoop to jump through http-remoting changes.

In terms of just using Calls and callbacks, the call interface is pretty hard to consume for the user (for example, a pain to mock, since you need to create a Response object which is final) and in a remoting world probably exposes too much to the user.

2017-05-25 19:10 UTC, j-baker commented
Stopping throwing exceptions - fine to do that, but this is rather little additional code to avoid the breaking change for consumers (and work required to communicate it) - 22 lines of code.

2017-05-25 19:58 UTC, uschi2000 commented
Spoke offline; I'm fine taking this. The CompletableFuture style is part of the standard retrofit game ( https://github.com/square/retrofit/blob/master/retrofit-adapters/java8/src/main/java/retrofit2/adapter/java8/Java8CallAdapterFactory.java ) and I agree they are more usable than Calls.

2017-05-25 19:59 UTC, uschi2000 approved these changes

2017-05-25 21:13 UTC, markelliot commented
Ok

From: Robert Fink <notifications@github.com>
Reply-To: palantir/http-remoting <reply@reply.github.com>
Date: Thursday, May 25, 2017 at 3:58 PM
To: palantir/http-remoting <http-remoting@noreply.github.com>
Cc: Mark Elliot <melliot@palantir.com>, Mention <mention@noreply.github.com>
Subject: Re: [palantir/http-remoting] Retrofit can return CompletableFutures (#436)


Spoke offline; I'm fine taking this. The CompletableFuture style is part of the standard retrofit game ( https://github.com/square/retrofit/blob/master/retrofit-adapters/java8/src/main/java/retrofit2/adapter/java8/Java8CallAdapterFactory.java[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_square_retrofit_blob_master_retrofit-2Dadapters_java8_src_main_java_retrofit2_adapter_java8_Java8CallAdapterFactory.java&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=1ERVcXVIrlQGb1GaPc0aXeBr0ACX3eJxLjo2DqIpTG8&s=RU5z5sYUdlQ9Aaaqv1Q3EQyMF4N7gdD0AIBVKa7eZeM&e=> ) and I agree they are more usable than Calls.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_http-2Dremoting_pull_436-23issuecomment-2D304107875&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=1ERVcXVIrlQGb1GaPc0aXeBr0ACX3eJxLjo2DqIpTG8&s=R50beR_h_lkuLhLXCZiXRrGdzQNM3KsHSiBG_P9po7E&e=>, or mute the thread[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAp3Qwpn4WPL1U82gAmCWmCTrHEIXj21ks5r9d1WgaJpZM4NlktB&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=1ERVcXVIrlQGb1GaPc0aXeBr0ACX3eJxLjo2DqIpTG8&s=oRS5IoTvig1MLJbP6h_YvODnnjuoSiwMI-i_6Gr-4Zc&e=>.

2017-05-25 21:38 UTC, merged