Revert "Stop propagating RemoteExceptions (#801)"
palantir/conjure-java-runtime pull request #852
Opened 2018-10-25 21:53 UTC by pnepywoda

This was a behavioral change without a major version bump and it's effects are far-reaching (clients will no longer get the exception names/codes they expect)

2018-11-01 21:45 UTC, bkrieger commented
+1

2018-11-05 14:13 UTC, iamdanfox requested changes
I don't want to prematurely revert this.

Discussion happening on https://github.com/palantir/conjure-java-runtime/issues/834.

2018-12-07 22:52 UTC, pnepywoda commented
@iamdanfox not-propagating exceptions is still a regression in functionality and it affects our ability to diagnose issues (when we see `Internal` instead of `RequestedItemNotFound` as the error name). 

I'm still strongly in-favor of reverting this until we've discussed an actual path forward that isn't a regression.

2018-12-07 23:02 UTC, pkoenig10 commented
I agree with @pnepywoda. Prior to this change there was not clear messaging that clients should not be introspecting upstream remote exceptions. While I don't disagree with the goal of the preventing this behavior, it appears that little consideration was given to the full consequences of this change. 

Upstream exceptions are still incredibly useful when used purely informationally (to provide error messages, etc.). When used in this way, clients aren't introspecting exception they shouldn't be but are still able to provide rich, useful error information.

2018-12-07 23:06 UTC, markelliot commented
We understand your position but as discussed on linked issues isn’t something this project is going to revert. We’d continue to note that if you value forwarding specific errors your service can absolutely continue to do so, explicitly.

2018-12-07 23:06 UTC, closed without merging